// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/gfm.css.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/ogp.png.ts";
import * as $4 from "./routes/report/[count].tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/gfm.css.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/ogp.png.ts": $3,
    "./routes/report/[count].tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
